env:
  es2021: true
  node: true
extends:
  - koa
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2021
plugins:
  - '@typescript-eslint'
rules: {
  'comma-dangle': ['error', 'never'],
  semi: [0], 'arrow-parens': [0] ,
  'space-before-function-paren': {
    anonymous: 'never',
    named: 'always'
  }
}
