env:
  commonjs: true
  es6: true
  node: true
extends:
  - koa
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
plugins:
  - '@typescript-eslint'
rules: { 'comma-dangle': ['error', 'never'], semi: [0], 'arrow-parens': [0] }
